name: ðŸ› Bug report
description: Something isn't working, uh?
title: Short description
labels: [bug]
body:
  - type: markdown
    attributes:
      value: >-
        <h1 align="center">!! IMPORTANT !! PLEASE READ</h1>
        
        
        # Media cannot be played / Unknown Error / Login required
        
        
        If you received one of these messages, chances are, YT is blocking you
        and it is not our fault. Please don't open a ticket for this.
        
        
        # Download unsuccessful
        
        
        If you click download (all or individually), and the download icons aren't changed. 
        Only open ticket if none of your songs downloaded.\
        If some are and some aren't, you are blocked by YT, please manually download them with
        some break time in between
        
        # Don't think that's YT? Read me
        
        
        If you can't play songs even on those you've downloaded, please try these steps:
        
        
        1. Re-download the song
        2. Clear cache
        3. Play songs that are physically on your device
        
        
        Then, if the problem persists. Please follow the steps below to open a ticket

  - type: markdown
    attributes:
      value: >-
        # Please complete the form to the best of your ability


        > Indepth details provide us foundation to fix your problem as fast as
        possible


        <h3 align="center">Required fields are marked with <b>*</b></h3>
  - type: input
    id: bug_occurs_in_version
    attributes:
      label: Version of RiMusic
      description: >-
        Before we start, please specify which version of RiMusic you were using
        when the bug occurs.
      placeholder: 0.6.56 - customVersion
    validations:
      required: true
  - type: markdown
    attributes:
      value: >-
        ## If you were using **_official release versions_**


        Please download and install [**latest
        build**](https://github.com/fast4x/RiMusic/releases/tag/custom-version)
        from our Github page.


        After the installation, try and reproduce the bug again.\

        If problem goes away, it's probably fixed at some point and is now
        waiting to be released officially.\

        There's no need to open another issue.


        ## If you were using latest **_custom version build_**


        Please **UNINSTALL** this build and install previous build and confirm
        that the problem persists.


        Proceed and fill out the form 
  - type: dropdown
    id: android_version
    attributes:
      label: Android version
      description: What version of Android is your phone
      options:
        - '7.0'
        - 7.1 - 7.1.2
        - '8.0'
        - '8.1'
        - '9'
        - '10'
        - '11'
        - '12'
        - '13'
        - '14'
        - '15'
    validations:
      required: true
  - type: checkboxes
    id: verify_steps
    attributes:
      label: 'I''ve done these:'
      description: >-
        please make sure you've done all of these steps before submitting an
        issue
      options:
        - label: Uninstall old build before installing a new one
          required: true
        - label: Checked opening issues about my similar problem
          required: true
  - type: markdown
    attributes:
      value: >-
        # Real questions


        Alright, now we've already applied some of the most common
        troubleshooting steps.


        Next step is to fill out the description of the bug. 

        Information such as:


        * Steps to duplicate the problem

        * How you expect it to be

        * What more can you tell us


        > These questions are really essential, the more you provide, the faster
        we can pin point the source of error, the faster we can patch it.
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Tell us how you trigger this bug
      description: 'Each step should be on its own line. You can use simple sentences like:'
      value: |-
        1. Open RiMusic
        2. Click on A 
        3. Click on B
        4. Boom! Crash happens
    validations:
      required: true
  - type: textarea
    id: evidence
    attributes:
      label: Submit a video
      description: 'Please record a short clip of the bug, it helps tremendously'
      value: |-
        If you are on Android, please download a screen recorder and record your screen while you
        duplicating the problem as describe above.
        
        > You may need to use Github App to be able to upload video - size limit is 10 MB.
        
        If you are on Desktop, drag video into this box and it will be uploaded automatically
    validations:
      required: false
  - type: input
    id: expected_behavior
    attributes:
      label: What was your expectation?
      description: What did you expect after completing those steps
      placeholder: I clicked on next so obviously it plays random. DUH!!
    validations:
      required: true
  - type: textarea
    id: additional_information
    attributes:
      label: What more can you tell us? (Optional)
      description: >-
        Please let me know what more you can provide in case other fields didn't
        let you fill in
      placeholder: >-
        I clicked on this, then uhhh, screen flickers, sound tears, and BOOM!
        app crashed.
  - type: textarea
    id: app_logs
    attributes:
      label: Logs (Optional)
      description: >-
        If you can still access app logs, please please please, copy it and
        paste it here.
  - type: markdown
    attributes:
      value: >-
        This template was generated with [Issue Forms
        Creator](https://issue-forms-creator.netlify.app)
