name: 🐛Bug report
description: Short description of how to trigger this bug
title: Name captures the problem
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: >-
        <h1 align="center">❗❗ IMPORTANT ❗❗</h1>

        <h2 align="center">PLEASE READ </h1>


        ---


        # Media cannot be played / Unknown Error / Login required


        If you received one of these messages, chances are, YouTube is blocking
        you and it is not our fault. Please don't open a ticket for this. We
        already know!



        # Download unsuccessful


        If you click download (all or individually), and the download icons
        aren't changed. 

        Only open ticket if none of your songs downloaded.


        If some are and some aren't, you are blocked by YouTube, please manually
        download them with some break time in between
                

        # Don't think that's YT?
                       
        If you can't play songs even on those you've downloaded, please try
        these steps:
                
        1. Re-download the song

        2. Clear cache

        3. Play songs that are physically on your device
                        
        Then, if the problem persists. Please follow the steps below to open a
        ticket


        ---
  - type: markdown
    attributes:
      value: >-
        # Please complete the form to the best of your ability


        > In-depth details will reduce bug finding process significantly, it
        gives us more reference to pinpoint the problem.


        ---


        Required fields are marked with *
  - type: input
    id: app-version
    attributes:
      label: Version of Kreate
      description: >-
        Please specify what version of Kreate are you on. Note: Don't use
        "latest" or similar terms, we have apps on multiple stores with some are
        lagged behind
      placeholder: v.1.0.0, v.1.1.0, etc.
    validations:
      required: true
  - type: dropdown
    id: android-version
    attributes:
      label: Android version
      description: What version of Android is your phone
      options:
        - 5.0 - 5.1.1 [LOLLIPOP]
        - 6 [M]
        - 7 - 7.1.x  [N]
        - 8 - 8.1 [O]
        - 9 [P]
        - 10 [Q]
        - 11 [R]
        - 12 - 12L [S]
        - 13 [TIRAMISU]
        - 14 [UPSIDE_DOWN_CAKE]
        - 15 [VANILLA_ICE_CREAM]
        - Other
    validations:
      required: true
  - type: input
    id: other-android-version
    attributes:
      label: Other Android version
      description: Only fill when you select "Other" in Android version
      placeholder: '16'
  - type: checkboxes
    id: required-actions
    attributes:
      label: TODOs before submitting a ticket
      description: Complete these steps fixes most problems, most of the time. Shocker!
      options:
        - label: Update my app to latest version (see link below)
          required: true
        - label: (If I'm on latest version) Re-install app
          required: true
        - label: I have checked issue page and there's no problem like mine
          required: true
  - type: markdown
    attributes:
      value: >-
        If you install Kreate with APK from releases page. Please go to
        [releases/lastest](https://github.com/knighthat/Kreate/releases) and
        check if it matches your install version.


        If you install from third-party app store, such as F-Droid. Please
        double check if there's update available on that app store. **If app
        store's version is lagged behind, please wait a few days to let them
        update it first, then you update the app.**


        > Please try to complete all of the tasks and not tick them because they
        are required.
  - type: markdown
    attributes:
      value: >
        ---


        # Real questions


        Alright, now we've already applied some of the most common
        troubleshooting steps. Next step is to fill out the description of the
        bug.


        > Remember! More information helps us resolve the problem faster
  - type: textarea
    id: bug-trigger
    attributes:
      label: Tell us how to trigger this bug
      description: 'Each step should be on its own line. You can use simple sentences like:'
      value: |-
        1. Open Kreate
        2. Click on A 
        3. Click on B
        4. Boom! Crash happens
    validations:
      required: true
  - type: textarea
    id: video
    attributes:
      label: Submit a video
      description: Please record a short clip of the bug, it helps tremendously
      value: >-
        Since Android 12, a screen recorder is baked into the OS, for your
        convenience! Older versions require additional software to do so.


        > Here's an [instruction
        video](https://www.youtube.com/watch?v=h6fOErvWIGI)
  - type: textarea
    id: expectation
    attributes:
      label: What was your expectation?
      description: What did you expect after completing those steps?
      placeholder: I clicked on next so obviously it plays random. DUH!!
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Logs (Optional)
      description: >-
        Logs can be enabled in Settings > Misc > "Enable debug logs" > "Copy
        crash log" (only available after you re-trigger the bug)
      value: |-
        <details>
          <summary>Logs</summary>
          [If you have multiple logs, please copy "details" for each log, name them appropriately, make sure they are different from each other]
          <Paste your log here>
        </details>
  - type: markdown
    attributes:
      value: >-
        This template was generated with [Issue Forms
        Creator](https://issue-forms-creator.netlify.app]
  - type: markdown
    attributes:
      value: >-
        This template was generated with [Issue Forms
        Creator](https://issue-forms-creator.netlify.app)
