name: Automatically update contributors.json

on:
  #schedule:
  #  - cron: '0 0 * * 1' # Every Monday @ 00:00
  # Allow manual trigger
  workflow_dispatch:

jobs:
  update-contributors:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4.2.0

      - name: Setup Python
        uses: actions/setup-python@v5.2.0

      - name: Get contributors
        run: "python get_developers.py"

      - name: Copy generated contributors.json to its correct place
        run: "mv contributors.json composeApp/src/androidMain/res/raw/contributors.json"
        
      - name: Get current date
        id: date
        #run: echo "::set-output name=date::$(date +'%m-%d-%Y')"
        run: echo "name=date::$(date +'%m-%d-%Y')" >> $GITHUB_OUTPUT

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: "updated ${{ steps.date.outputs.date }}"
